top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/generators
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/generators
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/generators

include $(top_srcdir)/build/special.mk

