top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

