top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/server/mpm
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/server/mpm
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
