top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/os/unix
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/os/unix
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
