top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/core
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/core
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/core

include $(top_srcdir)/build/special.mk

