top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/echo
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/echo
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/echo

include $(top_srcdir)/build/special.mk

