top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/os
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/os
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
