top_srcdir   = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
top_builddir = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43
srcdir       = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/lua
builddir     = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/lua
VPATH        = /restricted/projectnb/casa/_jychung/_gene2protein/httpd-2.4.43/modules/lua
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
